<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/kmb.dashboard.css') ?>
<?php $this->inlineScript()->prependFile($this->basePath() . '/js/kmb.dashboard.js'); ?>
<div class="row">
    <?php if ($this->environment != null): ?>
    <div class="col-md-7 pull-right text-right">
        <h3><?php echo $this->translate('Environment') ?> <small><?php echo $this->formatAncestorsNames($this->environment) ?></small></h3>
    </div>
    <?php endif ?>
    <div class="col-md-5">
        <div><?php echo $this->translate('Day Puppet statistics') ?></div>
        <div class="date"><?php echo $this->dateFormat(new DateTime(), IntlDateFormatter::TRADITIONAL, IntlDateFormatter::NONE) ?></div>
    </div>
</div>
<hr/>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading"><span class="glyphicon glyphicon-th"></span><span class="panel-break"></span><span id="os-distribution-title"></span></div>
            <div class="panel-body" id="os-distribution">
                <div class="row text-center" id="loading">
                    <p><img src="/images/wait.gif" alt="" /></p>
                    <p><?php echo $this->translate('Loading statistics ...'); ?></p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-4">
        <div class="panel panel-default">
            <div class="panel-heading"><span class="glyphicon glyphicon-list"></span><span class="panel-break"></span><?php echo $this->translate('Recently rebooted servers') ?></div>
            <ul class="list-group list-group-flush" id="recently-rebooted">
            </ul>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="panel panel-default">
            <div class="panel-heading"><span class="glyphicon glyphicon-list"></span><span class="panel-break"></span><?php echo $this->translate('Puppet informations') ?></div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item" id="unchanged-count"></li>
                <li class="list-group-item" id="changed-count"></li>
                <li class="list-group-item" id="failed-count"></li>
            </ul>
        </div>
    </div>
</div>
