<div class="row">
    <div class="col-md-3">
        <div><?php echo $this->translate('Day Puppet statistics') ?></div>
        <div class="date"><?php echo $this->dateFormat(new DateTime(), IntlDateFormatter::TRADITIONAL, IntlDateFormatter::NONE) ?></div>
    </div>
    <div class="col-md-3 info-bar">
        <div class="stats-title">
            <button class="btn btn-info btn-disabled"><span class="stats_puppet_skips"><?php echo $this->numberFormat($this->skips) ?></span> <?php echo $this->translatePlural('skip', 'skips', $this->skips) ?></button>
        </div>
    </div>
    <div class="col-md-3 info-bar">
        <div class="stats-title">
            <button class="btn btn-warning btn-disabled"><span class="stats_puppet_success"><?php echo $this->numberFormat($this->success) ?></span> <?php echo $this->translatePlural('change', 'changes', $this->success) ?></button>
        </div>
    </div>
    <div class="col-md-3 info-bar">
        <div class="stats-title">
            <button class="btn btn-danger btn-disabled"><span class="stats_puppet_failures"><?php echo $this->numberFormat($this->failures) ?></span> <?php echo $this->translatePlural('failure', 'failures', $this->failures) ?></button>
        </div>
    </div>
</div>
<?php if ($this->environment != null): ?>
<h3><?php echo $this->translate('Environment') ?> <small><?php echo $this->formatAncestorsNames($this->environment) ?></small></h3>
<?php endif ?>
<hr/>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading"><span class="glyphicon glyphicon-th"></span><span class="panel-break"></span><?php echo sprintf($this->translatePlural('%s server for %s OS', 'Distribution of the %s servers by %s OS', $this->nodesCount), '<span class="label label-info label-uniform">' . $this->numberFormat($this->nodesCount) . '</span>', $this->numberFormat($this->osCount)) ?></div>
            <div class="panel-body">
<?php foreach ($this->nodesCountByOS as $os => $nodesCount): ?>
                <div class="row">
                    <div class="col-lg-4"><span class="label label-info label-uniform"><?php echo $this->numberFormat($nodesCount) ?></span> <label><?php echo $os ?></label></div>
                    <div class="col-lg-8"><div class="progress"><div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: <?php echo $this->nodesPercentageByOS[$os] * 100 ?>%"><span><?php echo $this->numberFormat($this->nodesPercentageByOS[$os], NumberFormatter::PERCENT) ?></span></div></div></div>
                </div>
<?php endforeach ?>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-4">
        <div class="panel panel-default">
            <div class="panel-heading"><span class="glyphicon glyphicon-list"></span><span class="panel-break"></span><?php echo $this->translate('Recently rebooted servers') ?></div>
            <ul class="list-group list-group-flush" id="recently_rebooted">
<?php foreach ($this->recentlyRebootedNodes as $nodeName => $hour): ?>
                <li class="list-group-item"><span class="label label-warning label-uniform-large"><?php echo $hour ?></span>&nbsp;<a href="<?php echo $this->url('server', ['hostname' => $nodeName, 'action' => 'show'], ['query' => ['back' => $this->url('index', [], [], true)]], true) ?>"><?php echo $this->escapeHtml($nodeName) ?></a></li>
<?php endforeach ?>
            </ul>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="panel panel-default">
            <div class="panel-heading"><span class="glyphicon glyphicon-list"></span><span class="panel-break"></span><?php echo $this->translate('Puppet informations') ?></div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><span class="label label-success label-uniform"><?php echo $this->numberFormat($this->unchangedCount) ?></span> <?php echo $this->translatePlural('Unchanged server', 'Unchanged servers', $this->unchangedCount) ?></li>
                <li class="list-group-item"><span class="label label-warning label-uniform"><?php echo $this->numberFormat($this->changedCount) ?></span> <?php echo $this->translatePlural('Changed server', 'Changed servers', $this->changedCount) ?></li>
                <li class="list-group-item"><span class="label label-danger label-uniform"><?php echo $this->numberFormat($this->failedCount) ?></span> <?php echo $this->translatePlural('Failed server', 'Failed servers', $this->failedCount) ?></li>
            </ul>
        </div>
    </div>
</div>
